name: Rust

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
        rust: [nightly]

    steps:
    - uses: actions/checkout@v1
      with: 
         submodules: true
         rust-version: ${{ matrix.rust }}
    - name: Check rustup
      run:
         rustup show
    - name: Build
      run:
         cargo build
