name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with: 
         submodules: true
    - name: Check rustup
      run: rustup show
    - name: Build
      run:
         cargo build
