name: Unix

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest]

    steps:
    - uses: actions/checkout@v1
      with: 
         submodules: true
    - name: Install toolchain
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
    - name: Check rustup
      run: |
         . $HOME/.cargo/env
         rustup show
    - name: Build
      run: |
         . $HOME/.cargo/env
         cargo build
